# Generated by Django 6.0.2 on 2026-02-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('director', models.CharField(max_length=100)),
                ('release_year', models.IntegerField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
